service: lzd-cart-backend

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ap-northeast-2

functions:
  hello:
    handler: handler.hello