service: lzd-cart-backend

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ap-northeast-2

functions:
  getCart:
    handler: getCart.main
    events:
      - http:
          path: /lzd/cart/{id}
          method: get
          cors: true

  calculateCart:
    handler: calculateCart.main
    events:
      - http:
          path: /lzd/cart/calculate
          method: post
          cors: true
